from typing import Tuple


# xs_radii taken from smina codebase:
# https://github.com/mwojcikowski/smina/blob/2a4feb4afdc9c9fe289b54cd7e651aa583ffaf15/src/lib/atom_constants.h#L150
TYPES_TO_RADIUS = {
    "Hydrogen": 0.000000,
    "PolarHydrogen": 0.000000,
    "AliphaticCarbonXSHydrophobe": 1.900000,
    "AliphaticCarbonXSNonHydrophobe": 1.900000,
    "AromaticCarbonXSHydrophobe": 1.900000,
    "AromaticCarbonXSNonHydrophobe": 1.900000,
    "Nitrogen": 1.800000,
    "NitrogenXSDonor": 1.800000,
    "NitrogenXSDonorAcceptor": 1.800000,
    "NitrogenXSAcceptor": 1.800000,
    "Oxygen": 1.700000,
    "OxygenXSDonor": 1.700000,
    "OxygenXSDonorAcceptor": 1.700000,
    "OxygenXSAcceptor": 1.700000,
    "Sulfur": 2.000000,
    "SulfurAcceptor": 2.000000,
    "Phosphorus": 2.100000,
    "Fluorine": 1.500000,
    "Chlorine": 1.800000,
    "Bromine": 2.000000,
    "Iodine": 2.200000,
    "Magnesium": 1.200000,
    "Manganese": 1.200000,
    "Zinc": 1.200000,
    "Calcium": 1.200000,
    "Iron": 1.200000,
    "GenericMetal": 1.200000,
}

# CENsible requires atom-type/atom-type pairs to be in a specific order.
CENSIBLE_PAIRS = [
    ["AliphaticCarbonXSHydrophobe", "AliphaticCarbonXSHydrophobe"],
    ["AliphaticCarbonXSHydrophobe", "AliphaticCarbonXSNonHydrophobe"],
    ["AliphaticCarbonXSHydrophobe", "AromaticCarbonXSHydrophobe"],
    ["AliphaticCarbonXSHydrophobe", "AromaticCarbonXSNonHydrophobe"],
    ["AliphaticCarbonXSHydrophobe", "Bromine"],
    ["AliphaticCarbonXSHydrophobe", "Chlorine"],
    ["AliphaticCarbonXSHydrophobe", "Fluorine"],
    ["AliphaticCarbonXSHydrophobe", "GenericMetal"],
    ["AliphaticCarbonXSHydrophobe", "Magnesium"],
    ["AliphaticCarbonXSHydrophobe", "Manganese"],
    ["AliphaticCarbonXSHydrophobe", "Nitrogen"],
    ["AliphaticCarbonXSHydrophobe", "NitrogenXSAcceptor"],
    ["AliphaticCarbonXSHydrophobe", "NitrogenXSDonor"],
    ["AliphaticCarbonXSHydrophobe", "NitrogenXSDonorAcceptor"],
    ["AliphaticCarbonXSHydrophobe", "OxygenXSAcceptor"],
    ["AliphaticCarbonXSHydrophobe", "OxygenXSDonorAcceptor"],
    ["AliphaticCarbonXSHydrophobe", "Phosphorus"],
    ["AliphaticCarbonXSHydrophobe", "Sulfur"],
    ["AliphaticCarbonXSHydrophobe", "Zinc"],
    ["AliphaticCarbonXSNonHydrophobe", "AliphaticCarbonXSNonHydrophobe"],
    ["AliphaticCarbonXSNonHydrophobe", "AromaticCarbonXSHydrophobe"],
    ["AliphaticCarbonXSNonHydrophobe", "AromaticCarbonXSNonHydrophobe"],
    ["AliphaticCarbonXSNonHydrophobe", "Bromine"],
    ["AliphaticCarbonXSNonHydrophobe", "Calcium"],
    ["AliphaticCarbonXSNonHydrophobe", "Chlorine"],
    ["AliphaticCarbonXSNonHydrophobe", "Fluorine"],
    ["AliphaticCarbonXSNonHydrophobe", "GenericMetal"],
    ["AliphaticCarbonXSNonHydrophobe", "Magnesium"],
    ["AliphaticCarbonXSNonHydrophobe", "Manganese"],
    ["AliphaticCarbonXSNonHydrophobe", "Nitrogen"],
    ["AliphaticCarbonXSNonHydrophobe", "NitrogenXSAcceptor"],
    ["AliphaticCarbonXSNonHydrophobe", "NitrogenXSDonor"],
    ["AliphaticCarbonXSNonHydrophobe", "NitrogenXSDonorAcceptor"],
    ["AliphaticCarbonXSNonHydrophobe", "OxygenXSAcceptor"],
    ["AliphaticCarbonXSNonHydrophobe", "OxygenXSDonorAcceptor"],
    ["AliphaticCarbonXSNonHydrophobe", "Phosphorus"],
    ["AliphaticCarbonXSNonHydrophobe", "Sulfur"],
    ["AliphaticCarbonXSNonHydrophobe", "Zinc"],
    ["AromaticCarbonXSHydrophobe", "AromaticCarbonXSHydrophobe"],
    ["AromaticCarbonXSHydrophobe", "AromaticCarbonXSNonHydrophobe"],
    ["AromaticCarbonXSHydrophobe", "Bromine"],
    ["AromaticCarbonXSHydrophobe", "Chlorine"],
    ["AromaticCarbonXSHydrophobe", "Fluorine"],
    ["AromaticCarbonXSHydrophobe", "Nitrogen"],
    ["AromaticCarbonXSHydrophobe", "NitrogenXSAcceptor"],
    ["AromaticCarbonXSHydrophobe", "NitrogenXSDonor"],
    ["AromaticCarbonXSHydrophobe", "NitrogenXSDonorAcceptor"],
    ["AromaticCarbonXSHydrophobe", "OxygenXSAcceptor"],
    ["AromaticCarbonXSHydrophobe", "OxygenXSDonorAcceptor"],
    ["AromaticCarbonXSHydrophobe", "Phosphorus"],
    ["AromaticCarbonXSHydrophobe", "Sulfur"],
    ["AromaticCarbonXSNonHydrophobe", "AromaticCarbonXSNonHydrophobe"],
    ["AromaticCarbonXSNonHydrophobe", "Bromine"],
    ["AromaticCarbonXSNonHydrophobe", "Chlorine"],
    ["AromaticCarbonXSNonHydrophobe", "Fluorine"],
    ["AromaticCarbonXSNonHydrophobe", "Nitrogen"],
    ["AromaticCarbonXSNonHydrophobe", "NitrogenXSAcceptor"],
    ["AromaticCarbonXSNonHydrophobe", "NitrogenXSDonor"],
    ["AromaticCarbonXSNonHydrophobe", "NitrogenXSDonorAcceptor"],
    ["AromaticCarbonXSNonHydrophobe", "OxygenXSAcceptor"],
    ["AromaticCarbonXSNonHydrophobe", "OxygenXSDonorAcceptor"],
    ["AromaticCarbonXSNonHydrophobe", "Phosphorus"],
    ["AromaticCarbonXSNonHydrophobe", "Sulfur"],
    ["Nitrogen", "Chlorine"],
    ["Nitrogen", "Fluorine"],
    ["Nitrogen", "Nitrogen"],
    ["Nitrogen", "NitrogenXSAcceptor"],
    ["Nitrogen", "NitrogenXSDonor"],
    ["Nitrogen", "NitrogenXSDonorAcceptor"],
    ["Nitrogen", "OxygenXSAcceptor"],
    ["Nitrogen", "OxygenXSDonorAcceptor"],
    ["Nitrogen", "Phosphorus"],
    ["Nitrogen", "Sulfur"],
    ["Nitrogen", "Zinc"],
    ["NitrogenXSAcceptor", "Chlorine"],
    ["NitrogenXSAcceptor", "Fluorine"],
    ["NitrogenXSAcceptor", "NitrogenXSAcceptor"],
    ["NitrogenXSAcceptor", "OxygenXSAcceptor"],
    ["NitrogenXSAcceptor", "OxygenXSDonorAcceptor"],
    ["NitrogenXSAcceptor", "Phosphorus"],
    ["NitrogenXSAcceptor", "Sulfur"],
    ["NitrogenXSAcceptor", "Zinc"],
    ["NitrogenXSDonor", "Bromine"],
    ["NitrogenXSDonor", "Chlorine"],
    ["NitrogenXSDonor", "Fluorine"],
    ["NitrogenXSDonor", "NitrogenXSAcceptor"],
    ["NitrogenXSDonor", "NitrogenXSDonor"],
    ["NitrogenXSDonor", "NitrogenXSDonorAcceptor"],
    ["NitrogenXSDonor", "OxygenXSAcceptor"],
    ["NitrogenXSDonor", "OxygenXSDonorAcceptor"],
    ["NitrogenXSDonor", "Phosphorus"],
    ["NitrogenXSDonor", "Sulfur"],
    ["NitrogenXSDonor", "Zinc"],
    ["NitrogenXSDonorAcceptor", "NitrogenXSAcceptor"],
    ["NitrogenXSDonorAcceptor", "OxygenXSAcceptor"],
    ["NitrogenXSDonorAcceptor", "OxygenXSDonorAcceptor"],
    ["NitrogenXSDonorAcceptor", "Sulfur"],
    ["NitrogenXSDonorAcceptor", "Zinc"],
    ["OxygenXSAcceptor", "Bromine"],
    ["OxygenXSAcceptor", "Chlorine"],
    ["OxygenXSAcceptor", "Fluorine"],
    ["OxygenXSAcceptor", "Magnesium"],
    ["OxygenXSAcceptor", "Manganese"],
    ["OxygenXSAcceptor", "OxygenXSAcceptor"],
    ["OxygenXSAcceptor", "Phosphorus"],
    ["OxygenXSAcceptor", "Sulfur"],
    ["OxygenXSAcceptor", "Zinc"],
    ["OxygenXSDonorAcceptor", "Bromine"],
    ["OxygenXSDonorAcceptor", "Chlorine"],
    ["OxygenXSDonorAcceptor", "Fluorine"],
    ["OxygenXSDonorAcceptor", "Magnesium"],
    ["OxygenXSDonorAcceptor", "OxygenXSAcceptor"],
    ["OxygenXSDonorAcceptor", "OxygenXSDonorAcceptor"],
    ["OxygenXSDonorAcceptor", "Phosphorus"],
    ["OxygenXSDonorAcceptor", "Sulfur"],
    ["OxygenXSDonorAcceptor", "Zinc"],
    ["Phosphorus", "Magnesium"],
    ["Sulfur", "Bromine"],
    ["Sulfur", "Chlorine"],
    ["Sulfur", "Fluorine"],
    ["Sulfur", "Phosphorus"],
    ["Sulfur", "Sulfur"],
    ["Sulfur", "Zinc"],
    ["AliphaticCarbonXSHydrophobe", "Calcium"],
    ["AliphaticCarbonXSHydrophobe", "Iodine"],
    ["AliphaticCarbonXSHydrophobe", "Iron"],
    ["AliphaticCarbonXSHydrophobe", "Oxygen"],
    ["AliphaticCarbonXSHydrophobe", "OxygenXSDonor"],
    ["AliphaticCarbonXSHydrophobe", "SulfurAcceptor"],
    ["AliphaticCarbonXSNonHydrophobe", "Iodine"],
    ["AliphaticCarbonXSNonHydrophobe", "Iron"],
    ["AliphaticCarbonXSNonHydrophobe", "Oxygen"],
    ["AliphaticCarbonXSNonHydrophobe", "OxygenXSDonor"],
    ["AliphaticCarbonXSNonHydrophobe", "SulfurAcceptor"],
    ["AromaticCarbonXSHydrophobe", "Calcium"],
    ["AromaticCarbonXSHydrophobe", "GenericMetal"],
    ["AromaticCarbonXSHydrophobe", "Iodine"],
    ["AromaticCarbonXSHydrophobe", "Iron"],
    ["AromaticCarbonXSHydrophobe", "Magnesium"],
    ["AromaticCarbonXSHydrophobe", "Manganese"],
    ["AromaticCarbonXSHydrophobe", "Oxygen"],
    ["AromaticCarbonXSHydrophobe", "OxygenXSDonor"],
    ["AromaticCarbonXSHydrophobe", "SulfurAcceptor"],
    ["AromaticCarbonXSHydrophobe", "Zinc"],
    ["AromaticCarbonXSNonHydrophobe", "Calcium"],
    ["AromaticCarbonXSNonHydrophobe", "GenericMetal"],
    ["AromaticCarbonXSNonHydrophobe", "Iodine"],
    ["AromaticCarbonXSNonHydrophobe", "Iron"],
    ["AromaticCarbonXSNonHydrophobe", "Magnesium"],
    ["AromaticCarbonXSNonHydrophobe", "Manganese"],
    ["AromaticCarbonXSNonHydrophobe", "Oxygen"],
    ["AromaticCarbonXSNonHydrophobe", "OxygenXSDonor"],
    ["AromaticCarbonXSNonHydrophobe", "SulfurAcceptor"],
    ["AromaticCarbonXSNonHydrophobe", "Zinc"],
    ["Bromine", "Bromine"],
    ["Bromine", "Calcium"],
    ["Bromine", "GenericMetal"],
    ["Bromine", "Iodine"],
    ["Bromine", "Iron"],
    ["Bromine", "Magnesium"],
    ["Bromine", "Manganese"],
    ["Bromine", "Zinc"],
    ["Calcium", "Calcium"],
    ["Calcium", "GenericMetal"],
    ["Calcium", "Iron"],
    ["Chlorine", "Bromine"],
    ["Chlorine", "Calcium"],
    ["Chlorine", "Chlorine"],
    ["Chlorine", "GenericMetal"],
    ["Chlorine", "Iodine"],
    ["Chlorine", "Iron"],
    ["Chlorine", "Magnesium"],
    ["Chlorine", "Manganese"],
    ["Chlorine", "Zinc"],
    ["Fluorine", "Bromine"],
    ["Fluorine", "Calcium"],
    ["Fluorine", "Chlorine"],
    ["Fluorine", "Fluorine"],
    ["Fluorine", "GenericMetal"],
    ["Fluorine", "Iodine"],
    ["Fluorine", "Iron"],
    ["Fluorine", "Magnesium"],
    ["Fluorine", "Manganese"],
    ["Fluorine", "Zinc"],
    ["GenericMetal", "GenericMetal"],
    ["Iodine", "Calcium"],
    ["Iodine", "GenericMetal"],
    ["Iodine", "Iodine"],
    ["Iodine", "Iron"],
    ["Iodine", "Magnesium"],
    ["Iodine", "Manganese"],
    ["Iodine", "Zinc"],
    ["Iron", "GenericMetal"],
    ["Iron", "Iron"],
    ["Magnesium", "Calcium"],
    ["Magnesium", "GenericMetal"],
    ["Magnesium", "Iron"],
    ["Magnesium", "Magnesium"],
    ["Magnesium", "Manganese"],
    ["Magnesium", "Zinc"],
    ["Manganese", "Calcium"],
    ["Manganese", "GenericMetal"],
    ["Manganese", "Iron"],
    ["Manganese", "Manganese"],
    ["Manganese", "Zinc"],
    ["Nitrogen", "Bromine"],
    ["Nitrogen", "Calcium"],
    ["Nitrogen", "GenericMetal"],
    ["Nitrogen", "Iodine"],
    ["Nitrogen", "Iron"],
    ["Nitrogen", "Magnesium"],
    ["Nitrogen", "Manganese"],
    ["Nitrogen", "Oxygen"],
    ["Nitrogen", "OxygenXSDonor"],
    ["Nitrogen", "SulfurAcceptor"],
    ["NitrogenXSAcceptor", "Bromine"],
    ["NitrogenXSAcceptor", "Calcium"],
    ["NitrogenXSAcceptor", "GenericMetal"],
    ["NitrogenXSAcceptor", "Iodine"],
    ["NitrogenXSAcceptor", "Iron"],
    ["NitrogenXSAcceptor", "Magnesium"],
    ["NitrogenXSAcceptor", "Manganese"],
    ["NitrogenXSAcceptor", "Oxygen"],
    ["NitrogenXSAcceptor", "OxygenXSDonor"],
    ["NitrogenXSAcceptor", "SulfurAcceptor"],
    ["NitrogenXSDonor", "Calcium"],
    ["NitrogenXSDonor", "GenericMetal"],
    ["NitrogenXSDonor", "Iodine"],
    ["NitrogenXSDonor", "Iron"],
    ["NitrogenXSDonor", "Magnesium"],
    ["NitrogenXSDonor", "Manganese"],
    ["NitrogenXSDonor", "Oxygen"],
    ["NitrogenXSDonor", "OxygenXSDonor"],
    ["NitrogenXSDonor", "SulfurAcceptor"],
    ["NitrogenXSDonorAcceptor", "Bromine"],
    ["NitrogenXSDonorAcceptor", "Calcium"],
    ["NitrogenXSDonorAcceptor", "Chlorine"],
    ["NitrogenXSDonorAcceptor", "Fluorine"],
    ["NitrogenXSDonorAcceptor", "GenericMetal"],
    ["NitrogenXSDonorAcceptor", "Iodine"],
    ["NitrogenXSDonorAcceptor", "Iron"],
    ["NitrogenXSDonorAcceptor", "Magnesium"],
    ["NitrogenXSDonorAcceptor", "Manganese"],
    ["NitrogenXSDonorAcceptor", "NitrogenXSDonorAcceptor"],
    ["NitrogenXSDonorAcceptor", "Oxygen"],
    ["NitrogenXSDonorAcceptor", "OxygenXSDonor"],
    ["NitrogenXSDonorAcceptor", "Phosphorus"],
    ["NitrogenXSDonorAcceptor", "SulfurAcceptor"],
    ["Oxygen", "Bromine"],
    ["Oxygen", "Calcium"],
    ["Oxygen", "Chlorine"],
    ["Oxygen", "Fluorine"],
    ["Oxygen", "GenericMetal"],
    ["Oxygen", "Iodine"],
    ["Oxygen", "Iron"],
    ["Oxygen", "Magnesium"],
    ["Oxygen", "Manganese"],
    ["Oxygen", "Oxygen"],
    ["Oxygen", "OxygenXSAcceptor"],
    ["Oxygen", "OxygenXSDonor"],
    ["Oxygen", "OxygenXSDonorAcceptor"],
    ["Oxygen", "Phosphorus"],
    ["Oxygen", "Sulfur"],
    ["Oxygen", "SulfurAcceptor"],
    ["Oxygen", "Zinc"],
    ["OxygenXSAcceptor", "Calcium"],
    ["OxygenXSAcceptor", "GenericMetal"],
    ["OxygenXSAcceptor", "Iodine"],
    ["OxygenXSAcceptor", "Iron"],
    ["OxygenXSAcceptor", "SulfurAcceptor"],
    ["OxygenXSDonor", "Bromine"],
    ["OxygenXSDonor", "Calcium"],
    ["OxygenXSDonor", "Chlorine"],
    ["OxygenXSDonor", "Fluorine"],
    ["OxygenXSDonor", "GenericMetal"],
    ["OxygenXSDonor", "Iodine"],
    ["OxygenXSDonor", "Iron"],
    ["OxygenXSDonor", "Magnesium"],
    ["OxygenXSDonor", "Manganese"],
    ["OxygenXSDonor", "OxygenXSAcceptor"],
    ["OxygenXSDonor", "OxygenXSDonor"],
    ["OxygenXSDonor", "OxygenXSDonorAcceptor"],
    ["OxygenXSDonor", "Phosphorus"],
    ["OxygenXSDonor", "Sulfur"],
    ["OxygenXSDonor", "SulfurAcceptor"],
    ["OxygenXSDonor", "Zinc"],
    ["OxygenXSDonorAcceptor", "Calcium"],
    ["OxygenXSDonorAcceptor", "GenericMetal"],
    ["OxygenXSDonorAcceptor", "Iodine"],
    ["OxygenXSDonorAcceptor", "Iron"],
    ["OxygenXSDonorAcceptor", "Manganese"],
    ["OxygenXSDonorAcceptor", "SulfurAcceptor"],
    ["Phosphorus", "Bromine"],
    ["Phosphorus", "Calcium"],
    ["Phosphorus", "Chlorine"],
    ["Phosphorus", "Fluorine"],
    ["Phosphorus", "GenericMetal"],
    ["Phosphorus", "Iodine"],
    ["Phosphorus", "Iron"],
    ["Phosphorus", "Manganese"],
    ["Phosphorus", "Phosphorus"],
    ["Phosphorus", "Zinc"],
    ["Sulfur", "Calcium"],
    ["Sulfur", "GenericMetal"],
    ["Sulfur", "Iodine"],
    ["Sulfur", "Iron"],
    ["Sulfur", "Magnesium"],
    ["Sulfur", "Manganese"],
    ["Sulfur", "SulfurAcceptor"],
    ["SulfurAcceptor", "Bromine"],
    ["SulfurAcceptor", "Calcium"],
    ["SulfurAcceptor", "Chlorine"],
    ["SulfurAcceptor", "Fluorine"],
    ["SulfurAcceptor", "GenericMetal"],
    ["SulfurAcceptor", "Iodine"],
    ["SulfurAcceptor", "Iron"],
    ["SulfurAcceptor", "Magnesium"],
    ["SulfurAcceptor", "Manganese"],
    ["SulfurAcceptor", "Phosphorus"],
    ["SulfurAcceptor", "SulfurAcceptor"],
    ["SulfurAcceptor", "Zinc"],
    ["Zinc", "Calcium"],
    ["Zinc", "GenericMetal"],
    ["Zinc", "Iron"],
    ["Zinc", "Zinc"],
]
ANY_PAIR_TO_CENSIBLE_PAIR = {}
for t1, t2 in CENSIBLE_PAIRS:
    ANY_PAIR_TO_CENSIBLE_PAIR[(t1, t2)] = (t1, t2)
    ANY_PAIR_TO_CENSIBLE_PAIR[(t2, t1)] = (t1, t2)


def to_censible_pair(atom_type_pair: Tuple) -> Tuple[str, str]:
    """Converts a pair of atom types to a pair of atom types in the order
    required by CENsible.
    
    Args:
        atom_type_pair (Tuple): A pair of atom types.
        
    Returns:
        Tuple[str, str]: A pair of atom types in the order required by
        CENsible.
    """
    return ANY_PAIR_TO_CENSIBLE_PAIR[atom_type_pair]


def to_censible_key(atom_type_pair: Tuple) -> str:
    """Converts a pair of atom types to a string that can be used as a key in
    a dictionary, derived from the CENsible output file.
    
    Args:
        atom_type_pair (Tuple): A pair of atom types.
        
    Returns:
        str: A string that can be used as a key in a dictionary, derived from the
        CENsible output file.
    """
    atom_type_pair = to_censible_pair(atom_type_pair)
    return f"atom_type_gaussian(t1={atom_type_pair[0]},t2={atom_type_pair[1]},o=0,_w=1,_c=8)"
